#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Auto-generated from notebook. Wrapped as callable function.
"""

import os
os.makedirs('./output/data', exist_ok=True)
os.makedirs('./output/data/models', exist_ok=True)
os.makedirs('./output', exist_ok=True)


def run_reg_models(mode: str = "full"):
    """Run the pipeline step.

    Parameters
    ----------
    mode : str
        "full"      – run rolling-baseline regression and produce forecast parquet (default).
        "data-only" – skip entirely if the forecast output file already exists;
                      use cached regression predictions from the last full run.
    """
    import os as _os
    if mode == "data-only":
        _out = "./output/forecast_history_wide.parquet"
        if _os.path.exists(_out):
            print(f"[reg_models] data-only: usando cache → {_out}  (skipping regression)")
            return
        print(f"[reg_models] data-only: nenhum cache em {_out} — executando normalmente.")
    # -*- coding: utf-8 -*-
    """reg_Stock_modelos_individuais.ipynb

    Automatically generated by Colab.

    Original file is located at
        https://colab.research.google.com/drive/1_DSR7qHFz_6Rv0SOCMd8ocOGfkXBra7V
    """

    # ============================================================
    # v35-baseline-only (melhorado) — foco em confiabilidade
    #  - Split TRAIN/VALID/TEST com PURGE=HORIZON (evita leakage)
    #  - Seleção baseline (qroll/ewm-gauss + alpha) em VALID
    #  - Calib baseline (Huber) FIT no TRAIN
    #  - Banda assimétrica por resíduos:
    #      * resid quantiles (q_lo/q_hi)
    #      * band_scale calibrado com cross-fit walk-forward (multi-janelas)
    #      * fallback por asset_class
    #      * vol-adapt (regime recente)
    #  - 2 bandas: UNCAPPED (real) e CAPPED (operacional)
    #  - OpLevels (nível operacional p/ BUY/SELL)
    #  - Consolidação com Ensemble binário dd5/up20 -> signals_final.csv
    # ============================================================


    import sys
    # Dependencies should be pre-installed via requirements.txt / pip

    import os, json, time, glob, warnings
    from pathlib import Path
    import numpy as np
    import pandas as pd
    from tqdm.auto import tqdm
    from numeric_utils import normalize_before_save

    import yfinance as yf
    from sklearn.linear_model import HuberRegressor

    warnings.filterwarnings("ignore")
    np.random.seed(42)

    # =========================
    # CONFIG (ajuste aqui)
    # =========================
    STOCK_DIR    = "./output/data"
    PARQUET_PATH = "./output/data/expanded_stock_reduced.parquet"
    OUT_DIR_BASE = "./output/data/models"

    MODEL_TAG    = "v35_BASELINE_ONLY_IMPROVED_SPLIT_TEST_ASYM_BAND_VOLADAPT_WFCAL_CLASSFB_OPLEVELS_v4"
    SAVE_OUTPUTS = True

    REG_TARGETS = ["target_best_entry", "target_best_sale"]

    HORIZON    = 90
    PURGE_DAYS = HORIZON
    VAL_DAYS   = 90
    TEST_DAYS  = 90
    APPLY_DAYS = 5

    # --- Baseline quantile
    BASELINE_ROLL = 60
    BASELINE_MIN  = 40

    # --- Baseline EWM-Gauss
    USE_EWM_GAUSS = True
    EWM_HALFLIFE  = 252
    EWM_MINP      = 60

    # --- Vol-bounds (diferentes por target)
    USE_VOL_BOUNDS = True
    VOL_LOOKBACK   = 252
    VOL_K_ENTRY    = 2.3
    VOL_K_SALE     = 4.5

    # Hard caps (logret)
    HARD_ENTRY_LO_LOGRET = -0.65
    HARD_ENTRY_HI_LOGRET =  0.00
    HARD_SALE_LO_LOGRET  =  0.00
    HARD_SALE_HI_LOGRET  =  0.35

    # Auto-alpha candidates
    ENTRY_ALPHA_CANDS = [0.08, 0.10, 0.12, 0.15, 0.18]
    SALE_ALPHA_CANDS  = [0.82, 0.85, 0.88, 0.90, 0.92]
    ENTRY_ALPHA_CENTER = 0.12
    SALE_ALPHA_CENTER  = 0.88
    ALPHA_CENTER_PENALTY = 0.05
    ALPHA_ASYM_PENALTY   = 0.04

    # Caps em pct (híbrido)
    CAP_Q = 0.98
    CAP_Q_SMALL = 0.95
    CAP_MIN_SAMPLES = 220
    CAP_MAD_K = 10.0
    USE_HYBRID_CAP = True

    # clamp final de cap (por segurança)
    APPLY_CAP_MIN = 0.01
    APPLY_CAP_MAX = 0.42
    APPLY_ABS_CAP_MULT = 1.05

    # Score de seleção em VALID (baseline)
    TAIL_Q = 0.95
    BLEND_A_PIN = 0.20
    BLEND_B_P95 = 0.45
    CAP_HIT_MAX = 0.15
    CAP_HIT_PEN = 0.015

    # Calibração do baseline (FIT no TRAIN)
    USE_BASELINE_CALIB = True
    BASE_CALIB_A_CLIP = (-0.03, 0.03)
    BASE_CALIB_B_CLIP = (0.70, 1.30)
    CALIB_MIN_SAMPLES = 120

    # ===== Banda assimétrica (resíduos)
    RESID_Q_LO = 0.02
    RESID_Q_HI = 0.98

    # ===== Calibração do band_scale por cross-fit walk-forward (anti overfit)
    BAND_CAL_TARGET = 0.97              # alvo coverage no "calib windows"
    BAND_SCALE_MIN  = 0.50
    BAND_SCALE_MAX  = 25.0

    WF_N_WINDOWS    = 4                 # nº de janelas de calibração
    WF_WIN_DAYS     = 40                # tamanho de cada janela
    WF_STEP_DAYS    = 40                # passo (não sobrepõe)
    RESID_FIT_DAYS  = 756               # histórico (dias) para estimar quantis residuais
    MIN_FIT_SAMPLES = 220
    MIN_EVAL_SAMPLES= 25

    # ===== Vol-adapt (regime)
    VOLADAPT_ON  = True
    VOLADAPT_WIN = 60
    VOLADAPT_LONG= 252
    VOLADAPT_CLIP = (0.45, 2.60)

    # ===== OpLevels (nível operacional)
    # bias=0 -> center; bias=1 -> bound conservador (entry usa HI, sale usa LO)
    ENTRY_BIAS = 0.60
    SALE_BIAS  = 0.60

    # ===== Paths de saída “final”
    REG_APPLY_CSV_OUT   = "./output/apply_forecast_with_error_band.csv"
    ENSEMBLE_APPLY_CSV  = "./output/apply_ensemble_signals.csv"
    FINAL_SIGNALS_CSV   = "./output/signals_final.csv"
    RUN_CONSOLIDATION   = True


    # =========================
    # helpers
    # =========================
    def ensure_dir(p): Path(p).mkdir(parents=True, exist_ok=True)

    def logret_to_pct(x):
        x = np.asarray(x, dtype="float64")
        return np.expm1(x)

    def hard_caps_for_target_logret(tgt: str):
        if tgt == "target_best_entry":
            return HARD_ENTRY_LO_LOGRET, HARD_ENTRY_HI_LOGRET
        return HARD_SALE_LO_LOGRET, HARD_SALE_HI_LOGRET

    def hard_caps_for_target_pct(tgt: str):
        lo, hi = hard_caps_for_target_logret(tgt)
        return float(np.expm1(lo)), float(np.expm1(hi))

    def mae(y, p):
        y = np.asarray(y, dtype="float64"); p = np.asarray(p, dtype="float64")
        m = np.isfinite(y) & np.isfinite(p)
        if m.sum() == 0: return np.nan
        return float(np.mean(np.abs(y[m]-p[m])))

    def pquant_abs_err(y, p, q=0.95):
        y = np.asarray(y, dtype="float64"); p = np.asarray(p, dtype="float64")
        m = np.isfinite(y) & np.isfinite(p)
        if m.sum() == 0: return np.nan
        return float(np.quantile(np.abs(y[m]-p[m]), float(q)))

    def pinball_loss(y, p, alpha: float):
        y = np.asarray(y, dtype="float64")
        p = np.asarray(p, dtype="float64")
        m = np.isfinite(y) & np.isfinite(p)
        if m.sum() == 0: return np.nan
        u = y[m] - p[m]
        a = float(alpha)
        return float(np.mean(np.where(u >= 0, a*u, (1-a)*(-u))))

    def cap_hit_rate(pred, lo, hi):
        pred = np.asarray(pred, dtype="float64")
        m = np.isfinite(pred)
        if m.sum() == 0: return 1.0
        return float(np.mean((np.abs(pred[m]-lo) < 1e-12) | (np.abs(pred[m]-hi) < 1e-12)))

    def coverage_rate(y, lo, hi):
        y = np.asarray(y, dtype="float64")
        lo = np.asarray(lo, dtype="float64")
        hi = np.asarray(hi, dtype="float64")
        m = np.isfinite(y) & np.isfinite(lo) & np.isfinite(hi)
        if m.sum() == 0: return np.nan
        return float(np.mean((y[m] >= lo[m]) & (y[m] <= hi[m])))

    def touch_rate(y, center, lo, hi):
        # "touch": y cruza center -> e/ou encosta perto de bounds?
        y = np.asarray(y, dtype="float64")
        center = np.asarray(center, dtype="float64")
        lo = np.asarray(lo, dtype="float64")
        hi = np.asarray(hi, dtype="float64")
        m = np.isfinite(y) & np.isfinite(center) & np.isfinite(lo) & np.isfinite(hi)
        if m.sum() == 0: return np.nan
        # define "touch center": y está do outro lado do center (indicando que teria tocado)
        # para entry (neg) center é nível; para sale (pos) idem; é só um proxy direcional
        return float(np.mean(np.abs(y[m] - center[m]) <= np.abs(hi[m] - lo[m])))

    def pick_parquet(path_hint: str, stock_dir: str) -> str:
        if path_hint and os.path.exists(path_hint):
            return path_hint
        patterns = [
            os.path.join(stock_dir, "*quantile*.parquet"),
            os.path.join(stock_dir, "*reduced*.parquet"),
            os.path.join(stock_dir, "*.parquet"),
        ]
        seen = set()
        cands = []
        for pat in patterns:
            for p in glob.glob(pat):
                if p in seen: continue
                seen.add(p)
                try: mtime = os.path.getmtime(p)
                except Exception: mtime = 0
                score = 0
                name = os.path.basename(p).lower()
                if "quantile" in name: score += 50
                if "reduced"  in name: score += 10
                cands.append((score, mtime, p))
        if not cands:
            raise FileNotFoundError(f"Não achei nenhum .parquet em {stock_dir}.")
        cands.sort(key=lambda x: (x[0], x[1]), reverse=True)
        print("\n[auto] PARQUET_PATH não encontrado. Sugestões (top 10):")
        for i,(sc,mt,p) in enumerate(cands[:10],1):
            print(f"  {i:02d}) score={sc:02d} | mtime={time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(mt))} | {p}")
        chosen = cands[0][2]
        print(f"\n[auto] Usando: {chosen}\n")
        return chosen

    def find_close_col_for_ticker(df, tk):
        for c0 in ["Adj Close","Close","adj close","close","CLOSE","ADJ CLOSE"]:
            if (c0, tk) in df.columns:
                return (c0, tk)
        close_like = [c for c in df.columns if c[1] == tk and "close" in str(c[0]).lower()]
        return close_like[0] if close_like else None

    def is_good_close(s: pd.Series, min_frac=0.80, min_trading_days=250) -> bool:
        """Valida se uma série de fechamento tem dados suficientes para modelagem.
        Usa apenas preços positivos (exclui zeros pré-IPO), exige >= min_trading_days
        de pregões reais e mediana positiva. min_frac ainda é checado nos últimos
        2 anos (~504 pregões) para garantir continuidade recente."""
        if s is None: return False
        s_pos = s[s > 0]                       # apenas dias com pregão real (exclui zeros pré-IPO)
        if len(s_pos) < min_trading_days:      # exige ao menos ~1 ano de dados reais
            return False
        med = float(np.nanmedian(s_pos.values))
        if not (np.isfinite(med) and med > 0):
            return False
        # checar continuidade recente: nos últimos 504 dias, ao menos min_frac com preço > 0
        recent = s.iloc[-504:]
        frac_recent = float((recent > 0).mean())
        return frac_recent >= min_frac

    def asset_class(ticker: str) -> str:
        t = str(ticker)
        if t.endswith(".SA"):
            return "equity_br"
        if t.startswith("^"):
            return "index"
        if t.endswith("=X"):
            return "fx"
        if t.endswith("=F"):
            return "future"
        if "-USD" in t or t.endswith("USD"):
            return "crypto"
        return "other"

    def compute_vol_bound_logret(close_tr: pd.Series, horizon: int, lookback: int, k: float):
        c = close_tr.dropna()
        if len(c) < 80: return None
        r = np.log(c).diff().dropna().tail(lookback)
        if len(r) < 60: return None
        vol = float(np.nanstd(r.values))
        bound = float(k * vol * np.sqrt(max(1, horizon)))
        return bound

    def cap_max_pct_for(ticker: str, target: str, close_median: float | None = None) -> float:
        cls = asset_class(ticker)
        if cls == "fx":
            base = 0.10
        elif cls == "index":
            base = 0.12
        elif cls == "future":
            base = 0.28
        elif cls == "crypto":
            base = 0.35
        elif cls == "equity_br":
            base = 0.30
        else:
            base = 0.25

        if close_median is not None and np.isfinite(close_median):
            if close_median < 3.0:
                base = min(base, 0.22)
            elif close_median < 6.0:
                base = min(base, 0.26)

        if target == "target_best_entry":
            base = min(APPLY_CAP_MAX, max(base, 0.18))
        else:
            base = min(APPLY_CAP_MAX, max(base, 0.15))

        return float(np.clip(base, APPLY_CAP_MIN, APPLY_CAP_MAX))

    def mad_k_for(ticker: str) -> float:
        cls = asset_class(ticker)
        if cls in ("equity_br", "crypto", "future"):
            return 10.0
        return 10.0

    def hybrid_cap(arr, q, mad_k):
        a = np.asarray(arr, dtype="float64")
        a = a[np.isfinite(a)]
        if a.size == 0:
            return np.nan
        cap_q = float(np.quantile(a, q))
        med = float(np.median(a))
        mad = float(np.median(np.abs(a - med)))
        cap_rob = float(med + mad_k * mad)
        if not np.isfinite(cap_rob) or cap_rob <= 0:
            return cap_q
        return float(min(cap_q, cap_rob))

    def compute_caps_from_train_valid(
        y_tr_pct,
        y_va_pct,
        tgt,
        lo_pct_h,
        hi_pct_h,
        yq_lo_pct,
        yq_hi_pct,
        ticker: str | None = None,
        close_median: float | None = None,
    ):
        ntr = int(np.isfinite(y_tr_pct).sum())
        nva = int(np.isfinite(y_va_pct).sum())
        q_eff_tr = CAP_Q_SMALL if (ntr < CAP_MIN_SAMPLES) else CAP_Q
        q_eff_va = CAP_Q_SMALL if (nva < CAP_MIN_SAMPLES) else CAP_Q

        mk = CAP_MAD_K
        if ticker is not None:
            mk = mad_k_for(ticker)

        cap_max_asset = APPLY_CAP_MAX
        if ticker is not None:
            cap_max_asset = cap_max_pct_for(ticker, tgt, close_median=close_median)

        if tgt == "target_best_entry":
            dir_tr = np.abs(np.minimum(y_tr_pct, 0.0))
            dir_va = np.abs(np.minimum(y_va_pct, 0.0))

            if USE_HYBRID_CAP:
                cap_train = hybrid_cap(dir_tr, q_eff_tr, mk)
                cap_valid = hybrid_cap(dir_va, q_eff_va, mk)
            else:
                dtr = dir_tr[np.isfinite(dir_tr)]
                dva = dir_va[np.isfinite(dir_va)]
                cap_train = float(np.quantile(dtr, q_eff_tr)) if dtr.size else 0.20
                cap_valid = float(np.quantile(dva, q_eff_va)) if dva.size else cap_train

            if not np.isfinite(cap_train): cap_train = cap_valid
            if not np.isfinite(cap_valid): cap_valid = cap_train

            hard_abs = float(min(APPLY_CAP_MAX, abs(lo_pct_h)))
            yq_abs   = float(min(APPLY_CAP_MAX, abs(yq_lo_pct)))
            abs_limit = float(min(hard_abs, yq_abs, cap_max_asset))

            cap_ref = float(max(cap_train, cap_valid))
            cap_abs = APPLY_ABS_CAP_MULT * cap_ref
            cap_abs = float(np.clip(cap_abs, APPLY_CAP_MIN, abs_limit))
            return -cap_abs, 0.0, cap_abs

        else:
            dir_tr = np.maximum(y_tr_pct, 0.0)
            dir_va = np.maximum(y_va_pct, 0.0)

            if USE_HYBRID_CAP:
                cap_train = hybrid_cap(dir_tr, q_eff_tr, mk)
                cap_valid = hybrid_cap(dir_va, q_eff_va, mk)
            else:
                dtr = dir_tr[np.isfinite(dir_tr)]
                dva = dir_va[np.isfinite(dir_va)]
                cap_train = float(np.quantile(dtr, q_eff_tr)) if dtr.size else 0.20
                cap_valid = float(np.quantile(dva, q_eff_va)) if dva.size else cap_train

            if not np.isfinite(cap_train): cap_train = cap_valid
            if not np.isfinite(cap_valid): cap_valid = cap_train

            hard_hi = float(min(APPLY_CAP_MAX, hi_pct_h))
            yq_hi   = float(min(APPLY_CAP_MAX, yq_hi_pct))
            hi_limit = float(min(hard_hi, yq_hi, cap_max_asset))

            cap_ref = float(max(cap_train, cap_valid))
            cap_abs = APPLY_ABS_CAP_MULT * cap_ref
            cap_abs = float(np.clip(cap_abs, APPLY_CAP_MIN, hi_limit))
            return 0.0, cap_abs, cap_abs

    # --- Normal inverse CDF (Acklam) para z(alpha) sem scipy
    def norm_ppf(p: float) -> float:
        p = float(p)
        if p <= 0.0: return -np.inf
        if p >= 1.0: return  np.inf
        a = [-3.969683028665376e+01,  2.209460984245205e+02,
             -2.759285104469687e+02,  1.383577518672690e+02,
             -3.066479806614716e+01,  2.506628277459239e+00]
        b = [-5.447609879822406e+01,  1.615858368580409e+02,
             -1.556989798598866e+02,  6.680131188771972e+01,
             -1.328068155288572e+01]
        c = [-7.784894002430293e-03, -3.223964580411365e-01,
             -2.400758277161838e+00, -2.549732539343734e+00,
              4.374664141464968e+00,  2.938163982698783e+00]
        d = [ 7.784695709041462e-03,  3.224671290700398e-01,
              2.445134137142996e+00,  3.754408661907416e+00]
        plow = 0.02425
        phigh = 1 - plow
        if p < plow:
            q = np.sqrt(-2*np.log(p))
            return (((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5]) / \
                   ((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1)
        if p > phigh:
            q = np.sqrt(-2*np.log(1-p))
            return -(((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5]) / \
                     ((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1)
        q = p - 0.5
        r = q*q
        return (((((a[0]*r+a[1])*r+a[2])*r+a[3])*r+a[4])*r+a[5])*q / \
               (((((b[0]*r+b[1])*r+b[2])*r+b[3])*r+b[4])*r+1)

    # --- Baselines candidatos (sempre causais: shift(1))
    def baseline_quantile_roll(y_logret: pd.Series, alpha: float) -> pd.Series:
        a = float(alpha)
        base = y_logret.shift(1).rolling(BASELINE_ROLL, min_periods=BASELINE_MIN).quantile(a)
        base = base.fillna(y_logret.shift(1).expanding(min_periods=BASELINE_MIN).quantile(a))
        base = base.ffill().fillna(0.0).astype("float64")
        return base

    def baseline_ewm_gauss(y_logret: pd.Series, alpha: float) -> pd.Series:
        a = float(alpha)
        z = norm_ppf(a)
        ys = y_logret.shift(1).astype("float64")
        mu = ys.ewm(halflife=EWM_HALFLIFE, min_periods=EWM_MINP, adjust=False).mean()
        sd = ys.ewm(halflife=EWM_HALFLIFE, min_periods=EWM_MINP, adjust=False).std(bias=False)
        sd = sd.replace([np.inf, -np.inf], np.nan).fillna(0.0)
        base = (mu + z*sd).astype("float64").ffill().fillna(0.0)
        return base

    def split_dates_train_valid_test(y: pd.Series, all_dates: pd.DatetimeIndex):
        known = y.dropna().index
        if len(known) < (VAL_DAYS + TEST_DAYS + 350):
            return [], [], [], list(all_dates[-APPLY_DAYS:])

        test_end = len(known)
        test_start = max(0, test_end - TEST_DAYS)
        test_dates = known[test_start:test_end]

        # purge antes do test (evita overlap do label lookahead)
        valid_end = max(0, test_start - PURGE_DAYS)
        valid_start = max(0, valid_end - VAL_DAYS)
        valid_dates = known[valid_start:valid_end]

        # purge antes do valid
        train_end = max(0, valid_start - PURGE_DAYS)
        train_dates = known[:train_end]

        apply_dates = list(all_dates[-APPLY_DAYS:])
        return list(train_dates), list(valid_dates), list(test_dates), apply_dates


    def best_alpha_and_baseline_type(
        tk: str,
        tgt: str,
        y_logret: pd.Series,
        close_safe: pd.Series,
        train_dates: list,
        valid_dates: list,
    ):
        lo_h, hi_h = hard_caps_for_target_logret(tgt)
        lo_pct_h, hi_pct_h = hard_caps_for_target_pct(tgt)

        y_va_log = np.clip(y_logret.reindex(valid_dates).values.astype("float64"), lo_h, hi_h)
        y_va_pct = logret_to_pct(y_va_log)

        y_tr_log = np.clip(y_logret.reindex(train_dates).values.astype("float64"), lo_h, hi_h)
        y_tr_pct = logret_to_pct(y_tr_log)

        # vol-bound em logret
        yq_lo, yq_hi = lo_h, hi_h
        vol_bound = None
        if USE_VOL_BOUNDS:
            close_tr = close_safe.reindex(train_dates).ffill().bfill()
            k = VOL_K_ENTRY if tgt == "target_best_entry" else VOL_K_SALE
            vol_bound = compute_vol_bound_logret(close_tr, HORIZON, VOL_LOOKBACK, k)
            if vol_bound is not None and np.isfinite(vol_bound):
                vb = abs(float(vol_bound))
                if tgt == "target_best_entry":
                    yq_lo = max(yq_lo, -vb)
                    yq_hi = min(yq_hi, 0.0)
                else:
                    yq_lo = max(yq_lo, 0.0)
                    yq_hi = min(yq_hi, vb)

        yq_lo = float(np.clip(yq_lo, lo_h, hi_h))
        yq_hi = float(np.clip(yq_hi, lo_h, hi_h))
        yq_lo_pct = float(np.expm1(yq_lo))
        yq_hi_pct = float(np.expm1(yq_hi))

        close_median = float(np.nanmedian(close_safe.reindex(train_dates).values))
        cap_lo, cap_hi, cap_abs = compute_caps_from_train_valid(
            y_tr_pct=y_tr_pct,
            y_va_pct=y_va_pct,
            tgt=tgt,
            lo_pct_h=lo_pct_h,
            hi_pct_h=hi_pct_h,
            yq_lo_pct=yq_lo_pct,
            yq_hi_pct=yq_hi_pct,
            ticker=tk,
            close_median=close_median,
        )

        cands = ENTRY_ALPHA_CANDS if tgt == "target_best_entry" else SALE_ALPHA_CANDS
        center = ENTRY_ALPHA_CENTER if tgt == "target_best_entry" else SALE_ALPHA_CENTER

        base_types = ["qroll"]
        if USE_EWM_GAUSS:
            base_types.append("ewmgauss")

        best = None
        y_tr = y_logret.reindex(train_dates).astype("float64").clip(lo_h, hi_h)

        for bt in base_types:
            for a in cands:
                a = float(a)

                base = baseline_quantile_roll(y_logret, a) if bt == "qroll" else baseline_ewm_gauss(y_logret, a)
                base = base.clip(lo_h, hi_h).clip(yq_lo, yq_hi)

                # calib (train)
                cal_a, cal_b = 0.0, 1.0
                base_cal = base.copy()

                if USE_BASELINE_CALIB:
                    xb = base.reindex(train_dates).values.astype("float64")
                    yb = y_tr.values.astype("float64")
                    m = np.isfinite(xb) & np.isfinite(yb)
                    if m.sum() >= CALIB_MIN_SAMPLES:
                        try:
                            hr = HuberRegressor(alpha=0.0, epsilon=1.35)
                            hr.fit(xb[m].reshape(-1,1), yb[m])
                            cal_a = float(np.clip(hr.intercept_, BASE_CALIB_A_CLIP[0], BASE_CALIB_A_CLIP[1]))
                            cal_b = float(np.clip(hr.coef_[0],    BASE_CALIB_B_CLIP[0], BASE_CALIB_B_CLIP[1]))
                            base_cal = (cal_a + cal_b * base_cal).astype("float64")
                        except Exception:
                            cal_a, cal_b = 0.0, 1.0
                            base_cal = base.copy()

                base_cal = base_cal.clip(lo_h, hi_h)
                if tgt == "target_best_entry":
                    base_cal = np.minimum(base_cal.values, 0.0)
                else:
                    base_cal = np.maximum(base_cal.values, 0.0)
                base_cal = pd.Series(base_cal, index=base.index).clip(yq_lo, yq_hi)

                pred_va_log = base_cal.reindex(valid_dates).values.astype("float64")
                pred_va_log = np.clip(pred_va_log, lo_h, hi_h)
                pred_va_pct = logret_to_pct(pred_va_log)

                pred_va_pct = np.clip(pred_va_pct, lo_pct_h, hi_pct_h)
                pred_va_pct = np.clip(pred_va_pct, yq_lo_pct, yq_hi_pct)
                pred_va_pct = np.clip(pred_va_pct, cap_lo, cap_hi)

                mae_f = mae(y_va_pct, pred_va_pct)
                p95_f = pquant_abs_err(y_va_pct, pred_va_pct, TAIL_Q)
                pin_f = pinball_loss(y_va_pct, pred_va_pct, a)
                hit   = cap_hit_rate(pred_va_pct, cap_lo, cap_hi)

                if not (np.isfinite(mae_f) and np.isfinite(p95_f) and np.isfinite(pin_f)):
                    continue

                pen_center = ALPHA_CENTER_PENALTY * abs(a - float(center))
                if tgt == "target_best_sale":
                    pen_asym = ALPHA_ASYM_PENALTY * max(0.0, a - float(center))
                else:
                    pen_asym = ALPHA_ASYM_PENALTY * max(0.0, float(center) - a)

                score = float(mae_f) + BLEND_A_PIN*float(pin_f) + BLEND_B_P95*float(p95_f)
                score += float(pen_center) + float(pen_asym)
                score += CAP_HIT_PEN * max(0.0, float(hit) - float(CAP_HIT_MAX))

                cand = {
                    "score": float(score),
                    "baseline_type": bt,
                    "alpha": float(a),
                    "cal_a": float(cal_a),
                    "cal_b": float(cal_b),
                    "mae_valid": float(mae_f),
                    "p95_valid": float(p95_f),
                    "pin_valid": float(pin_f),
                    "cap_hit_valid": float(hit),
                    "cap_lo": float(cap_lo),
                    "cap_hi": float(cap_hi),
                    "cap_abs": float(cap_abs),
                    "yq_lo": float(yq_lo),
                    "yq_hi": float(yq_hi),
                    "yq_lo_pct": float(yq_lo_pct),
                    "yq_hi_pct": float(yq_hi_pct),
                    "vol_bound": float(vol_bound) if vol_bound is not None else None,
                }
                if best is None or cand["score"] < best["score"]:
                    best = cand

        return best


    # =========================
    # RUN HEADER
    # =========================
    print(f"MODE=baseline_only | MODEL_TAG={MODEL_TAG}")
    print(f"HORIZON={HORIZON} | VAL_DAYS={VAL_DAYS} | TEST_DAYS={TEST_DAYS} | APPLY_DAYS={APPLY_DAYS} | PURGE={PURGE_DAYS}")
    print(f"Baseline: roll_q({BASELINE_ROLL}) + ewm_gauss={USE_EWM_GAUSS}(HL={EWM_HALFLIFE}) | calib={USE_BASELINE_CALIB}")
    print(f"VolBounds={USE_VOL_BOUNDS}(K_entry={VOL_K_ENTRY}, K_sale={VOL_K_SALE}) | CAP_Q={CAP_Q} HYBRID={USE_HYBRID_CAP}")
    print(f"AsymBand: resid q[{RESID_Q_LO:.02f},{RESID_Q_HI:.02f}] | WFcal target={BAND_CAL_TARGET} | scale in [{BAND_SCALE_MIN},{BAND_SCALE_MAX}]")
    print(f"VolAdapt: {VOLADAPT_ON} win={VOLADAPT_WIN} clip={VOLADAPT_CLIP}")
    print(f"OpLevels: entry_bias={ENTRY_BIAS} | sale_bias={SALE_BIAS}")

    # =========================
    # [1] Load parquet
    # =========================
    PARQUET_PATH = pick_parquet(PARQUET_PATH, STOCK_DIR)

    print("\n[1/7] Carregando parquet...")
    df = pd.read_parquet(PARQUET_PATH)
    if not isinstance(df.columns, pd.MultiIndex):
        raise ValueError("Parquet deve ter MultiIndex (level0=feature/target, level1=ticker).")
    if not isinstance(df.index, pd.DatetimeIndex):
        df.index = pd.to_datetime(df.index)
    df = df.sort_index()

    lvl0 = df.columns.get_level_values(0).astype(str)
    lvl1 = df.columns.get_level_values(1).astype(str)

    tickers_valid = sorted(set(lvl1[lvl0 == REG_TARGETS[0]]) & set(lvl1[lvl0 == REG_TARGETS[1]]))
    print(f"  ✓ Tickers válidos: {len(tickers_valid)}")

    ALL_DATES = df.index
    INVALID_Y_DATES = set(ALL_DATES[-HORIZON:]) if len(ALL_DATES) >= HORIZON else set(ALL_DATES)

    # =========================
    # [2] Close series
    # =========================
    print("\n[2/7] Preparando Close...")
    close_map = {}
    missing_close = []
    for tk in tickers_valid:
        cc = find_close_col_for_ticker(df, tk)
        if cc is None:
            missing_close.append(tk)
        else:
            close_map[tk] = pd.to_numeric(df[cc], errors="coerce").astype("float64")

    if missing_close:
        print(f"  ⚠️ Close não encontrado no parquet para {len(missing_close)} tickers. Baixando via yfinance (auto_adjust=True)...")
        tmp = yf.download(
            missing_close,
            start=str(df.index.min().date()),
            end=str((df.index.max() + pd.Timedelta(days=1)).date()),
            group_by="column",
            auto_adjust=True,
            progress=False,
            threads=True,
        )
        tmp_close = None
        if isinstance(tmp.columns, pd.MultiIndex):
            if "Close" in tmp.columns.get_level_values(0):
                tmp_close = tmp["Close"]
            elif "Adj Close" in tmp.columns.get_level_values(0):
                tmp_close = tmp["Adj Close"]
        else:
            tmp_close = tmp.rename("Close").to_frame()

        if tmp_close is not None:
            for tk in missing_close:
                if tk not in tmp_close.columns:
                    continue
                s = tmp_close[tk].reindex(df.index).ffill().bfill()
                close_map[tk] = pd.to_numeric(s, errors="coerce").astype("float64")

    bad_close = [tk for tk,s in close_map.items() if not is_good_close(s)]
    for tk in bad_close:
        close_map.pop(tk, None)

    tickers_valid = [tk for tk in tickers_valid if tk in close_map]
    if bad_close:
        print(f"  ⚠️ Removidos por Close inválido ({len(bad_close)}): {bad_close[:10]}{'...' if len(bad_close)>10 else ''}")
    print(f"  ✓ Close disponível para {len(close_map)} tickers")

    # =========================
    # [3] Preparar séries e escolher baseline (tipo+alpha+calib)
    # =========================
    print("\n[3/7] Preparando séries e escolhendo baseline + banda WFcal/class-fallback...")
    prepared = {}
    meta_best = {}

    for tk in tqdm(tickers_valid, desc="Tickers", leave=False):
        close = close_map.get(tk)
        if close is None:
            continue

        close_safe = close.replace(0, np.nan).ffill().bfill().astype("float64")

        for tgt in REG_TARGETS:
            col = (tgt, tk)
            if col not in df.columns:
                continue

            lo_h, hi_h = hard_caps_for_target_logret(tgt)
            target_abs = pd.to_numeric(df[col], errors="coerce").astype("float64")

            t_med = np.nanmedian(target_abs.values)
            c_med = np.nanmedian(close_safe.values)
            already_returnish = (np.isfinite(t_med) and np.isfinite(c_med) and (abs(t_med) < 0.8) and (c_med > 3.0))

            if already_returnish:
                y_logret = target_abs.copy()
            else:
                y_logret = np.log(target_abs / close_safe)

            y_logret = (y_logret.replace([np.inf,-np.inf], np.nan)
                               .clip(-1.0, 1.0)
                               .clip(lo_h, hi_h)
                               .astype("float64"))

            y_logret.loc[list(INVALID_Y_DATES)] = np.nan

            train_dates, valid_dates, test_dates, apply_dates = split_dates_train_valid_test(y_logret, ALL_DATES)
            if len(train_dates) < 300 or len(valid_dates) < 50 or len(test_dates) < 50:
                continue

            best = best_alpha_and_baseline_type(
                tk=tk, tgt=tgt, y_logret=y_logret, close_safe=close_safe,
                train_dates=train_dates, valid_dates=valid_dates
            )
            if best is None:
                continue

            # pré-computa center prediction (pct) para toda a série (1x)
            bt = best["baseline_type"]
            alpha = float(best["alpha"])
            cal_a = float(best["cal_a"])
            cal_b = float(best["cal_b"])
            yq_lo = float(best["yq_lo"])
            yq_hi = float(best["yq_hi"])
            cap_lo = float(best["cap_lo"])
            cap_hi = float(best["cap_hi"])
            lo_pct_h, hi_pct_h = hard_caps_for_target_pct(tgt)
            yq_lo_pct = float(best["yq_lo_pct"]); yq_hi_pct = float(best["yq_hi_pct"])

            base = baseline_quantile_roll(y_logret, alpha) if bt == "qroll" else baseline_ewm_gauss(y_logret, alpha)
            pred_log = (cal_a + cal_b*base).astype("float64")
            pred_log = pred_log.clip(lo_h, hi_h)
            if tgt == "target_best_entry":
                pred_log = np.minimum(pred_log.values, 0.0)
            else:
                pred_log = np.maximum(pred_log.values, 0.0)
            pred_log = pd.Series(pred_log, index=base.index).clip(yq_lo, yq_hi)

            pred_pct_center = logret_to_pct(pred_log.values.astype("float64"))
            pred_pct_center = np.clip(pred_pct_center, lo_pct_h, hi_pct_h)
            pred_pct_center = np.clip(pred_pct_center, yq_lo_pct, yq_hi_pct)
            pred_pct_center = np.clip(pred_pct_center, cap_lo, cap_hi)

            y_true_log = y_logret.values.astype("float64")
            y_true_log = np.clip(y_true_log, lo_h, hi_h)
            y_true_pct = logret_to_pct(y_true_log)

            # vol-adapt factor baseado no close (regime)
            vol_factor = np.ones(len(ALL_DATES), dtype="float64")
            if VOLADAPT_ON:
                r = np.log(close_safe).diff()
                v1 = r.rolling(VOLADAPT_WIN,  min_periods=max(20, VOLADAPT_WIN//3)).std()
                v2 = r.rolling(VOLADAPT_LONG, min_periods=max(60, VOLADAPT_LONG//3)).std()
                ratio = (v1 / v2).replace([np.inf,-np.inf], np.nan).fillna(1.0).values.astype("float64")
                ratio = np.clip(ratio, VOLADAPT_CLIP[0], VOLADAPT_CLIP[1])
                vol_factor = ratio

            prepared[(tk, tgt)] = {
                "ticker": tk,
                "target": tgt,
                "asset_class": asset_class(tk),
                "y_logret": y_logret,
                "y_true_pct_full": pd.Series(y_true_pct, index=ALL_DATES),
                "pred_pct_center_full": pd.Series(pred_pct_center, index=ALL_DATES),
                "vol_factor_full": pd.Series(vol_factor, index=ALL_DATES),
                "close": close_safe,
                "train_dates": train_dates,
                "valid_dates": valid_dates,
                "test_dates": test_dates,
                "apply_dates": apply_dates,
                "best": best,
            }

            meta_best[f"{tk}|||{tgt}"] = best

    print(f"  ✓ Séries preparadas: {len(prepared)} (ticker,target)")

    # =========================
    # [4] Calibração WF do band_scale + fallback por asset_class
    # =========================
    def resid_quantiles_from_dates(pack, fit_dates):
        y = pack["y_true_pct_full"].reindex(fit_dates).values.astype("float64")
        p = pack["pred_pct_center_full"].reindex(fit_dates).values.astype("float64")
        m = np.isfinite(y) & np.isfinite(p)
        if m.sum() < MIN_FIT_SAMPLES:
            return None
        resid = (y[m] - p[m]).astype("float64")
        qlo = float(np.quantile(resid, RESID_Q_LO))
        qhi = float(np.quantile(resid, RESID_Q_HI))
        return qlo, qhi, int(m.sum())

    def interval_uncapped(pack, dates, qlo, qhi, scale):
        tgt = pack["target"]
        best = pack["best"]

        pred = pack["pred_pct_center_full"].reindex(dates).values.astype("float64")
        vf   = pack["vol_factor_full"].reindex(dates).values.astype("float64")

        lo_pct_h, hi_pct_h = hard_caps_for_target_pct(tgt)
        yq_lo_pct = float(best["yq_lo_pct"]); yq_hi_pct = float(best["yq_hi_pct"])

        s = float(scale)
        lo = pred + (s * vf) * float(qlo)
        hi = pred + (s * vf) * float(qhi)

        # direção do target
        if tgt == "target_best_entry":
            hi = np.minimum(hi, 0.0)
        else:
            lo = np.maximum(lo, 0.0)

        # hard/yq
        lo = np.clip(lo, lo_pct_h, hi_pct_h)
        hi = np.clip(hi, lo_pct_h, hi_pct_h)
        lo = np.clip(lo, yq_lo_pct, yq_hi_pct)
        hi = np.clip(hi, yq_lo_pct, yq_hi_pct)

        # garante lo<=hi
        lo2 = np.minimum(lo, hi)
        hi2 = np.maximum(lo, hi)
        return lo2, hi2

    def find_scale_for_target_cov(pack, eval_dates, qlo, qhi, cov_target, lo_s=BAND_SCALE_MIN, hi_s=BAND_SCALE_MAX):
        y = pack["y_true_pct_full"].reindex(eval_dates).values.astype("float64")
        m = np.isfinite(y)
        if m.sum() < MIN_EVAL_SAMPLES:
            return None

        # coverage monotônica ~ escala
        lo = float(lo_s)
        hi = float(hi_s)
        for _ in range(20):
            mid = 0.5*(lo+hi)
            L, H = interval_uncapped(pack, eval_dates, qlo, qhi, mid)
            cov = coverage_rate(y, L, H)
            if not np.isfinite(cov):
                return None
            if cov >= cov_target:
                hi = mid
            else:
                lo = mid
        return float(hi)

    def wf_calibrate_scale(pack):
        # gera janelas “para trás” terminando no final do VALID
        valid_dates = pack["valid_dates"]
        if len(valid_dates) < 50:
            return None

        valid_end = valid_dates[-1]
        known = pack["y_logret"].dropna().index

        scales = []
        # define endpoints por data (no eixo do known)
        for i in range(WF_N_WINDOWS):
            # janela de avaliação termina recuando i*WF_STEP_DAYS dentro do VALID
            end_dt = valid_end - pd.Timedelta(days=i*WF_STEP_DAYS)
            start_dt = end_dt - pd.Timedelta(days=WF_WIN_DAYS)

            eval_dates = [d for d in known if (d >= start_dt and d <= end_dt)]
            if len(eval_dates) < MIN_EVAL_SAMPLES:
                continue

            fit_end_dt = start_dt - pd.Timedelta(days=PURGE_DAYS)
            fit_start_dt = fit_end_dt - pd.Timedelta(days=RESID_FIT_DAYS)
            fit_dates = [d for d in known if (d >= fit_start_dt and d <= fit_end_dt)]
            rq = resid_quantiles_from_dates(pack, fit_dates)
            if rq is None:
                continue
            qlo, qhi, nfit = rq
            s = find_scale_for_target_cov(pack, eval_dates, qlo, qhi, BAND_CAL_TARGET)
            if s is not None and np.isfinite(s):
                scales.append(s)

        if len(scales) == 0:
            return None
        return float(np.median(scales))


    print("\n[4/7] Calibrando band_scale com WF cross-fit + fallback por asset_class...")
    pair_band = {}
    scales_by_class = {}  # (asset_class, target) -> list of scales

    for (tk, tgt), pack in tqdm(sorted(prepared.items()), desc="WFCal"):
        s = wf_calibrate_scale(pack)
        pair_band[(tk, tgt)] = {"band_scale_raw": s}
        cls = pack["asset_class"]
        if s is not None and np.isfinite(s):
            scales_by_class.setdefault((cls, tgt), []).append(float(s))

    # mediana por classe/target
    class_scale = {}
    for k, arr in scales_by_class.items():
        if len(arr) >= 5:
            class_scale[k] = float(np.median(arr))

    # fallback global por target
    global_scale = {}
    for tgt in REG_TARGETS:
        all_s = [v["band_scale_raw"] for (tk2,tgt2),v in pair_band.items() if tgt2==tgt and v["band_scale_raw"] is not None and np.isfinite(v["band_scale_raw"])]
        global_scale[tgt] = float(np.median(all_s)) if len(all_s) else 1.0

    # aplica fallback
    for (tk, tgt), pack in prepared.items():
        cls = pack["asset_class"]
        s = pair_band[(tk,tgt)]["band_scale_raw"]
        if s is None or not np.isfinite(s):
            s2 = class_scale.get((cls,tgt), None)
            if s2 is None:
                s2 = global_scale.get(tgt, 1.0)
            pair_band[(tk,tgt)]["band_scale_raw"] = float(s2)
            pair_band[(tk,tgt)]["band_scale_fallback"] = True
        else:
            pair_band[(tk,tgt)]["band_scale_fallback"] = False

    print("  ✓ band_scale: WF+fallback pronto.")

    # =========================
    # [5] Gerar VALID, TEST e APPLY (com banda)
    # =========================
    print("\n[5/7] Gerando VALID, TEST e APPLY...")

    def build_frames_for_pair(pack):
        tk  = pack["ticker"]
        tgt = pack["target"]
        best = pack["best"]

        dates_valid = pack["valid_dates"]
        dates_test  = pack["test_dates"]
        dates_apply = list(ALL_DATES[-APPLY_DAYS:])

        close = pack["close"]

        pred_center = pack["pred_pct_center_full"]
        y_true = pack["y_true_pct_full"]

        # resid quantiles: fit até o fim do TRAIN+VALID com purge antes do TEST (evita overlap)
        known = pack["y_logret"].dropna().index
        # fit_end = último dia do VALID (seguro por PURGE no split)
        fit_end = pack["valid_dates"][-1]
        fit_start = fit_end - pd.Timedelta(days=RESID_FIT_DAYS)
        fit_dates = [d for d in known if (d >= fit_start and d <= fit_end)]
        rq = resid_quantiles_from_dates(pack, fit_dates)
        if rq is None:
            # fallback: usa resid muito “apertado”
            qlo, qhi, nfit = -0.05, 0.05, 0
        else:
            qlo, qhi, nfit = rq

        scale_raw = float(pair_band[(tk,tgt)]["band_scale_raw"])
        used_fb = bool(pair_band[(tk,tgt)]["band_scale_fallback"])

        # bounds uncapped/capped para um conjunto de datas
        def make_df(dates, label):
            pred = pred_center.reindex(dates).values.astype("float64")
            y    = y_true.reindex(dates).values.astype("float64")

            L_u, H_u = interval_uncapped(pack, dates, qlo, qhi, scale_raw)

            # capped (operacional)
            cap_lo = float(best["cap_lo"]); cap_hi = float(best["cap_hi"])
            L_c = np.clip(L_u, cap_lo, cap_hi)
            H_c = np.clip(H_u, cap_lo, cap_hi)

            # center “operacional” (para touch/compare)
            pred_c = np.clip(pred, cap_lo, cap_hi)

            # OpLevels: entry usa HI (mais perto do preço), sale usa LO
            if tgt == "target_best_entry":
                op = (1.0-ENTRY_BIAS)*pred_c + ENTRY_BIAS*H_c
            else:
                op = (1.0-SALE_BIAS)*pred_c + SALE_BIAS*L_c

            # preços (reconstrói close por Date)
            close_d = close.reindex(dates).ffill().bfill().values.astype("float64")

            df_out = pd.DataFrame({
                "Date": dates,
                "ticker": tk,
                "target": tgt,
                "asset_class": pack["asset_class"],
                "model": f"baseline_{best['baseline_type']}_a{best['alpha']:.2f}_cal({best['cal_a']:+.3f},{best['cal_b']:.3f})",
                "used_ml": False,
                "alpha": float(best["alpha"]),
                "band_q_lo": float(RESID_Q_LO),
                "band_q_hi": float(RESID_Q_HI),
                "resid_q_lo": float(qlo),
                "resid_q_hi": float(qhi),
                "resid_fit_n": int(nfit),
                "band_scale": float(scale_raw),
                "band_scale_fallback": bool(used_fb),
                "cap_lo": float(best["cap_lo"]),
                "cap_hi": float(best["cap_hi"]),
                "pred_pct_center": pred_c,
                "pred_pct_lo_uncapped": L_u,
                "pred_pct_hi_uncapped": H_u,
                "pred_pct_lo_capped": L_c,
                "pred_pct_hi_capped": H_c,
                "op_pct": op,
                "y_true_pct": y,
            })

            df_out["pred_price_center"]      = close_d * (1.0 + df_out["pred_pct_center"].astype("float64"))
            df_out["pred_price_lo_uncapped"] = close_d * (1.0 + df_out["pred_pct_lo_uncapped"].astype("float64"))
            df_out["pred_price_hi_uncapped"] = close_d * (1.0 + df_out["pred_pct_hi_uncapped"].astype("float64"))
            df_out["pred_price_lo_capped"]   = close_d * (1.0 + df_out["pred_pct_lo_capped"].astype("float64"))
            df_out["pred_price_hi_capped"]   = close_d * (1.0 + df_out["pred_pct_hi_capped"].astype("float64"))
            df_out["op_price"]               = close_d * (1.0 + df_out["op_pct"].astype("float64"))

            # erros (só onde y_true existe)
            df_out["abs_err_pct"] = np.abs(df_out["pred_pct_center"] - df_out["y_true_pct"])
            return df_out

        vdf = make_df(dates_valid, "VALID")
        tdf = make_df(dates_test, "TEST")
        adf = make_df(dates_apply, "APPLY")

        # métricas por par (VALID/TEST)
        def summarize(df_cmp):
            y = df_cmp["y_true_pct"].values.astype("float64")
            p = df_cmp["pred_pct_center"].values.astype("float64")
            m = np.isfinite(y) & np.isfinite(p)
            if m.sum() == 0:
                return {"mae": np.nan, "p95": np.nan, "covU": np.nan, "covC": np.nan, "cap_hit": np.nan, "touchC": np.nan, "touchOp": np.nan}
            y2 = y[m]; p2 = p[m]
            mae_v = float(np.mean(np.abs(y2-p2)))
            p95_v = float(np.quantile(np.abs(y2-p2), 0.95))

            covU = coverage_rate(y, df_cmp["pred_pct_lo_uncapped"].values, df_cmp["pred_pct_hi_uncapped"].values)
            covC = coverage_rate(y, df_cmp["pred_pct_lo_capped"].values,   df_cmp["pred_pct_hi_capped"].values)

            cap_hit = cap_hit_rate(df_cmp["pred_pct_center"].values, float(best["cap_lo"]), float(best["cap_hi"]))

            touchC  = touch_rate(y, df_cmp["pred_pct_center"].values,
                                 df_cmp["pred_pct_lo_capped"].values, df_cmp["pred_pct_hi_capped"].values)
            touchOp = touch_rate(y, df_cmp["op_pct"].values,
                                 df_cmp["pred_pct_lo_capped"].values, df_cmp["pred_pct_hi_capped"].values)

            return {"mae": mae_v, "p95": p95_v, "covU": covU, "covC": covC, "cap_hit": cap_hit, "touchC": touchC, "touchOp": touchOp}

        smv = summarize(vdf)
        smt = summarize(tdf)

        # injeta métricas do par (constantes) no APPLY (pra você ter “nota”)
        for k,v in {
            "mae_valid": smv["mae"], "p95_valid": smv["p95"], "covU_valid": smv["covU"], "covC_valid": smv["covC"],
            "mae_test":  smt["mae"], "p95_test":  smt["p95"], "covU_test":  smt["covU"], "covC_test":  smt["covC"],
            "touchC_valid": smv["touchC"], "touchOp_valid": smv["touchOp"],
            "touchC_test":  smt["touchC"], "touchOp_test":  smt["touchOp"],
        }.items():
            adf[k] = v

        return vdf, tdf, adf


    valid_frames, test_frames, apply_frames = [], [], []

    for (tk, tgt), pack in tqdm(sorted(prepared.items()), desc="Compare"):
        vdf, tdf, adf = build_frames_for_pair(pack)
        if vdf is not None and not vdf.empty:
            valid_frames.append(vdf)
        if tdf is not None and not tdf.empty:
            test_frames.append(tdf)
        if adf is not None and not adf.empty:
            apply_frames.append(adf)

    VALID_COMPARE = pd.concat(valid_frames, axis=0).sort_values(["Date","ticker","target"]) if valid_frames else pd.DataFrame()
    TEST_COMPARE  = pd.concat(test_frames,  axis=0).sort_values(["Date","ticker","target"]) if test_frames  else pd.DataFrame()
    APPLY_VIEW    = pd.concat(apply_frames, axis=0).sort_values(["Date","ticker","target"]) if apply_frames else pd.DataFrame()

    print(f"  ✓ VALID_COMPARE rows: {len(VALID_COMPARE)}")
    print(f"  ✓ TEST_COMPARE  rows: {len(TEST_COMPARE)}")
    print(f"  ✓ APPLY_VIEW    rows: {len(APPLY_VIEW)}")

    def summarize_block(df_cmp: pd.DataFrame, name="VALID_COMPARE"):
        if df_cmp is None or df_cmp.empty:
            print(f"\n===== {name} =====\n(vazio)")
            return
        y = df_cmp["y_true_pct"].values.astype("float64")
        p = df_cmp["pred_pct_center"].values.astype("float64")
        m = np.isfinite(y) & np.isfinite(p)
        if m.sum() == 0:
            print(f"\n===== {name} =====\n(sem amostras finitas)")
            return
        y = y[m]; p = p[m]
        mae_g = float(np.mean(np.abs(y-p)))
        p95_g = float(np.quantile(np.abs(y-p), 0.95))
        covU = coverage_rate(df_cmp["y_true_pct"].values, df_cmp["pred_pct_lo_uncapped"].values, df_cmp["pred_pct_hi_uncapped"].values)
        covC = coverage_rate(df_cmp["y_true_pct"].values, df_cmp["pred_pct_lo_capped"].values,   df_cmp["pred_pct_hi_capped"].values)

        hit_list = []
        for _,g in df_cmp.groupby(["ticker","target"]):
            lo = float(g["cap_lo"].iloc[0]); hi = float(g["cap_hi"].iloc[0])
            hit_list.append(cap_hit_rate(g["pred_pct_center"].values, lo, hi))
        cap_hit_g = float(np.mean(hit_list)) if hit_list else np.nan

        print(f"\n===== {name} (GERAL) =====")
        print(f"rows (com y_true): {int(m.sum())}")
        print(f"MAE: {mae_g:.6f}   (≈ {100*mae_g:.2f} p.p.)")
        print(f"P95 abs err: {p95_g:.6f}   (≈ {100*p95_g:.2f} p.p.)")
        print(f"coverage UNCAPPED: {covU:.3f}")
        print(f"coverage CAPPED   : {covC:.3f}")
        print(f"cap_hit_rate (média por ticker/target): {cap_hit_g:.3f}")

        print(f"\n===== {name} por target =====")
        for tgt in sorted(df_cmp["target"].unique()):
            gg = df_cmp[df_cmp["target"] == tgt]
            y2 = gg["y_true_pct"].values.astype("float64")
            p2 = gg["pred_pct_center"].values.astype("float64")
            mm = np.isfinite(y2) & np.isfinite(p2)
            if mm.sum() == 0:
                print(f" {tgt} | (sem amostras)")
                continue
            mae_t = float(np.mean(np.abs(y2[mm]-p2[mm])))
            p95_t = float(np.quantile(np.abs(y2[mm]-p2[mm]), 0.95))
            covU_t = coverage_rate(gg["y_true_pct"].values, gg["pred_pct_lo_uncapped"].values, gg["pred_pct_hi_uncapped"].values)
            covC_t = coverage_rate(gg["y_true_pct"].values, gg["pred_pct_lo_capped"].values,   gg["pred_pct_hi_capped"].values)
            hit_list_t = []
            for _,g in gg.groupby(["ticker","target"]):
                lo = float(g["cap_lo"].iloc[0]); hi = float(g["cap_hi"].iloc[0])
                hit_list_t.append(cap_hit_rate(g["pred_pct_center"].values, lo, hi))
            cap_hit_t = float(np.mean(hit_list_t)) if hit_list_t else np.nan
            print(f" {tgt} | MAE={mae_t:.6f} (~{100*mae_t:.2f}pp) | P95={p95_t:.6f} (~{100*p95_t:.2f}pp) | covU={covU_t:.3f} | covC={covC_t:.3f} | cap_hit={cap_hit_t:.3f}")

    summarize_block(VALID_COMPARE, "VALID_COMPARE")
    summarize_block(TEST_COMPARE,  "TEST_COMPARE")

    # =========================
    # [6] Save outputs
    # =========================
    print("\n[6/7] Salvando outputs...")
    OUT_DIR = os.path.join(OUT_DIR_BASE, f"{MODEL_TAG}_outputs")
    ensure_dir(OUT_DIR)

    if SAVE_OUTPUTS:
        normalize_before_save(pd.DataFrame([
            {
                "ticker": k.split("|||")[0],
                "target": k.split("|||")[1],
                **{f"best_{kk}": vv for kk,vv in v.items()}
            }
            for k,v in meta_best.items()
        ])).to_csv(os.path.join(OUT_DIR, "baseline_best_by_ticker_target.csv"), index=False)

        # salva band scale
        rows = []
        for (tk,tgt), d in pair_band.items():
            rows.append({
                "ticker": tk,
                "target": tgt,
                "asset_class": asset_class(tk),
                "band_scale": d.get("band_scale_raw", np.nan),
                "fallback_used": d.get("band_scale_fallback", False)
            })
        normalize_before_save(pd.DataFrame(rows)).to_csv(os.path.join(OUT_DIR, "band_scale_by_ticker_target.csv"), index=False)

        if not VALID_COMPARE.empty:
            normalize_before_save(VALID_COMPARE).to_csv(os.path.join(OUT_DIR, "valid_compare.csv"), index=False)
        if not TEST_COMPARE.empty:
            normalize_before_save(TEST_COMPARE).to_csv(os.path.join(OUT_DIR, "test_compare.csv"), index=False)
        if not APPLY_VIEW.empty:
            normalize_before_save(APPLY_VIEW).to_csv(os.path.join(OUT_DIR, "apply_forecast_with_error_band.csv"), index=False)

        with open(os.path.join(OUT_DIR, "meta_best.json"), "w") as f:
            json.dump(meta_best, f, indent=2)

    print("\n[Concluído ✅]")
    print(f"📁 Outputs em: {OUT_DIR}")

    # Export “final” para a raiz do Drive (pra consolidar fácil)
    if not APPLY_VIEW.empty:
        normalize_before_save(APPLY_VIEW).to_csv(REG_APPLY_CSV_OUT, index=False)
        print(f"✅ APPLY exportado para: {REG_APPLY_CSV_OUT}")

    # ============================================================
    # [EXTRA] Export FULL/HISTORY forecast (FORMATO WIDE / LARGO)
    # ============================================================
    # Gera um arquivo com colunas separadas para COMPRA e VENDA na mesma linha.
    # Colunas: Date, ticker, best_buy_price, buy_err_lo, buy_err_hi, best_sell_price, sell_err_lo, sell_err_hi
    # ============================================================

    SAVE_HISTORY_FORECAST = True
    REG_HISTORY_PARQUET = "./output/forecast_history_wide.parquet"
    REG_HISTORY_CSV     = "./output/forecast_history_wide.csv"
    HISTORY_STREAM_PARQUET = True

    # Definição exata das colunas de saída
    HISTORY_WIDE_COLS = [
        "Date", "ticker",
        "best_buy_price", "buy_err_lo", "buy_err_hi",
        "best_sell_price", "sell_err_lo", "sell_err_hi"
    ]

    def get_arrays_for_pack(pack, dates):
        """
        Função auxiliar para calcular OpPrice e Bandas (Erro) para um pack específico
        Retorna arrays numpy: op_price, band_lo_price, band_hi_price
        """
        if pack is None:
            return np.full(len(dates), np.nan), np.full(len(dates), np.nan), np.full(len(dates), np.nan)

        tk  = pack["ticker"]
        tgt = pack["target"]
        best = pack["best"]
        close = pack["close"]
        pred_center = pack["pred_pct_center_full"]

        # 1. Recuperar quantis residuais (fit no valid)
        known = pack["y_logret"].dropna().index
        fit_end = pack["valid_dates"][-1]
        fit_start = fit_end - pd.Timedelta(days=RESID_FIT_DAYS)
        fit_dates = [d for d in known if (d >= fit_start and d <= fit_end)]

        rq = resid_quantiles_from_dates(pack, fit_dates)
        if rq is None:
            qlo, qhi = -0.05, 0.05
        else:
            qlo, qhi, _ = rq

        # 2. Calcular bandas uncapped (Erro Puro)
        scale_raw = float(pair_band[(tk,tgt)]["band_scale_raw"])
        L_u, H_u = interval_uncapped(pack, dates, qlo, qhi, scale_raw)

        # 3. Calcular OpLevel (Preço Operacional)
        cap_lo = float(best["cap_lo"]); cap_hi = float(best["cap_hi"])
        pred = pred_center.reindex(dates).values.astype("float64")

        # Clip operational parts
        L_c = np.clip(L_u, cap_lo, cap_hi)
        H_c = np.clip(H_u, cap_lo, cap_hi)
        pred_c = np.clip(pred, cap_lo, cap_hi)

        if tgt == "target_best_entry":
            op_pct = (1.0-ENTRY_BIAS)*pred_c + ENTRY_BIAS*H_c
        else:
            op_pct = (1.0-SALE_BIAS)*pred_c + SALE_BIAS*L_c

        # 4. Converter tudo para PREÇO
        close_d = close.reindex(dates).ffill().bfill().values.astype("float64")

        op_price = close_d * (1.0 + op_pct)
        err_lo_price = close_d * (1.0 + L_u)
        err_hi_price = close_d * (1.0 + H_u)

        return op_price, err_lo_price, err_hi_price

    def build_wide_history_for_ticker(tk):
        dates = list(ALL_DATES)

        # Pega os pacotes de Compra e Venda
        pack_buy  = prepared.get((tk, "target_best_entry"))
        pack_sell = prepared.get((tk, "target_best_sale"))

        # Calcula vetores
        buy_op, buy_lo, buy_hi   = get_arrays_for_pack(pack_buy, dates)
        sell_op, sell_lo, sell_hi = get_arrays_for_pack(pack_sell, dates)

        # Monta DataFrame único
        df = pd.DataFrame({
            "Date": dates,
            "ticker": tk,
            "best_buy_price": buy_op,
            "buy_err_lo": buy_lo,
            "buy_err_hi": buy_hi,
            "best_sell_price": sell_op,
            "sell_err_lo": sell_lo,
            "sell_err_hi": sell_hi
        })

        return df[HISTORY_WIDE_COLS]

    if SAVE_HISTORY_FORECAST:
        print("\n[history] Exporting WIDE FORMAT regression forecast...")

        use_parquet = False
        writer = None
        rows_written = 0

        if HISTORY_STREAM_PARQUET:
            try:
                import pyarrow as pa
                import pyarrow.parquet as pq
                use_parquet = True
            except Exception:
                use_parquet = False

        chunks_csv = []

        # Identificar lista única de tickers
        unique_tickers = sorted(list(set(k[0] for k in prepared.keys())))

        for i, tk in enumerate(unique_tickers):
            hdf = build_wide_history_for_ticker(tk)

            if use_parquet:
                table = pa.Table.from_pandas(hdf, preserve_index=False)
                if writer is None:
                    writer = pq.ParquetWriter(REG_HISTORY_PARQUET, table.schema, compression="snappy")
                writer.write_table(table)
            else:
                chunks_csv.append(hdf)

            rows_written += len(hdf)
            if (i % 10) == 0:
                print(f"  - tickers processed: {i+1}/{len(unique_tickers)} | rows={rows_written:,}")

        if writer is not None:
            writer.close()
            print(f"[saved] {REG_HISTORY_PARQUET} (rows={rows_written:,})")
        elif chunks_csv:
            hist_df = pd.concat(chunks_csv, axis=0).sort_values(["Date","ticker"])
            normalize_before_save(hist_df).to_csv(REG_HISTORY_CSV, index=False)
            print(f"[saved] {REG_HISTORY_CSV} (rows={rows_written:,})")

    import pandas as pd

    # Caminho definido no seu código anterior
    parquet_path = "./output/forecast_history_wide.parquet"

    try:
        # 1. Carrega o arquivo
        df_lido = pd.read_parquet(parquet_path)

        # 2. Mostra a lista de colunas
        print("=== Colunas no Arquivo ===")
        print(df_lido.columns.tolist())

        # 3. Mostra as primeiras 5 linhas para conferir os dados
        print("\n=== Primeiras 5 linhas ===")
        print(df_lido.head())

    except FileNotFoundError:
        print(f"Arquivo não encontrado em: {parquet_path}")
        print("Verifique se o código anterior terminou de rodar e se o Drive está montado.")



if __name__ == '__main__':
    run_reg_models()
