#!/usr/bin/env bash
# Instala post-commit hook no worktree CODEX que chama sync_codex_to_main.sh
# sempre que um commit novo for feito no worktree codex (branch codex/*).
#
# Git hooks nao sao versionados (ficam em .git/hooks/), entao esse script
# instala localmente. Re-rodar e idempotente (sobrescreve).
#
# Uso:
#   bash scripts/install_codex_sync_hook.sh
#
# Como o worktree codex compartilha .git com main, o hook detecta qual
# worktree disparou o commit via pwd + branch name, e so sincroniza
# quando o commit vem da branch codex/*.
set -euo pipefail

CODEX_WORKTREE="${CODEX_WORKTREE:-C:/Users/gabri/.codex/worktrees/0b30/test}"
MAIN_REPO="${MAIN_REPO:-C:/Users/gabri/OneDrive/Documentos/GitHub/test}"

if [ ! -d "$CODEX_WORKTREE" ]; then
  echo "[install] Codex worktree nao encontrado: $CODEX_WORKTREE"
  exit 1
fi

# .git em worktree e um arquivo que aponta pra pasta real dos hooks
git_dir=$(git -C "$CODEX_WORKTREE" rev-parse --git-dir)
# No Windows git-bash, o path pode vir relativo/absoluto misturado
if [[ "$git_dir" != /* ]] && [[ "$git_dir" != [A-Za-z]:* ]]; then
  git_dir="$CODEX_WORKTREE/$git_dir"
fi
hook_path="$git_dir/hooks/post-commit"

mkdir -p "$git_dir/hooks"

cat > "$hook_path" <<HOOK
#!/usr/bin/env bash
# Auto-generated by scripts/install_codex_sync_hook.sh
# Fires on every commit; only syncs when commit is on codex/* branch.
set -eu

branch=\$(git symbolic-ref --short HEAD 2>/dev/null || echo "")
cwd_basename=\$(basename "\$PWD" 2>/dev/null || echo "")

# Fire only from codex worktree (branch starts with 'codex/')
case "\$branch" in
  codex/*)
    # export para sync script saber o worktree
    export CODEX_WORKTREE="$CODEX_WORKTREE"
    export MAIN_REPO="$MAIN_REPO"
    # Run in background so commit returns fast; logs to /tmp
    nohup bash "$MAIN_REPO/scripts/sync_codex_to_main.sh" \\
      > /tmp/codex_sync_\$(date +%s).log 2>&1 &
    echo "[codex-sync] background sync iniciado (log em /tmp/codex_sync_*.log)"
    ;;
  *)
    ;;
esac
HOOK

chmod +x "$hook_path"
echo "[install] hook instalado em: $hook_path"
echo "[install] proximo commit no worktree codex (branch codex/*) vai disparar sync automatico."
echo ""
echo "Para testar manualmente:"
echo "  bash $MAIN_REPO/scripts/sync_codex_to_main.sh"
echo ""
echo "Para ativar push automatico apos sync:"
echo "  export GA_SYNC_PUSH=1"
